#!/usr/bin/env python

top = ".."

def build(bld):
	bld(export_includes="private", name="rove_inc")

	objs = []
	obj = lambda src: objs.append(src)

	obj("list.c")
	obj("settings.c")
	obj("config_parser.c")

	obj("group.c")
	obj("file_loop.c")
	obj("pattern.c")
	obj("session.c")

	obj("jack.c")
	obj("monome.c")

	obj("rove.c")
    
	bld.program(
		target="rove",
		source=objs,

		use="rove_inc LIBMONOME JACK SNDFILE SAMPLERATE",
		lib=["m", "pthread"])
